[package]
name = "synesthesia"
version = "0.1.0"
authors = ["Curtis Maves <curtismaves@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["ham-xpt"]

control = ["ecp"]
ham-xpt = ["control", "ham"]
jack-source = ["jack"]


[dependencies]
ecp = {git="https://github.com/cmaves/ecp.git", optional=true }
ham = {git="https://github.com/cmaves/ham.git", optional=true }
jack = { version = "0.6.0", optional = true }
rustfft = "3.0.1"
lazy_static = "1.4.0"
